const GET_DRIVERS = 'GET_DRIVERS'
const GET_DRIVER_BY_NAME = 'GET_DRIVER_BY_NAME'
const GET_TEAMS = 'GET_TEAMS'
const GET_NATIONALITIES = 'GET_NATIONALITIES'
const GET_NATIONALITY_FLAG = 'GET_NATIONALITY_FLAG'
const CLEAR_NATIONALITY_FLAG = 'CLEAR_NATIONALITY_FLAG'
const FILTER_BY_TEAMS = 'FILTER_BY_TEAMS'
const FILTER_BY_DB = 'FILTER_BY_DB'
const ORDER_BY_NAME = 'ORDER_BY_NAME'
const ORDER_BY_DOB = 'ORDER_BY_DOB'



export {
  GET_DRIVERS,
  GET_DRIVER_BY_NAME,
  GET_TEAMS,
  GET_NATIONALITIES,
  GET_NATIONALITY_FLAG,
  CLEAR_NATIONALITY_FLAG,
  FILTER_BY_TEAMS,
  FILTER_BY_DB,
  ORDER_BY_NAME,
  ORDER_BY_DOB
}